#!/usr/bin/env python3

import json
import math
import datetime
from pathlib import Path

from videos_processing import Video

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Extract a thumbnail from each scene of a video.')
    parser.add_argument('metadata_filename',
        help='The filename of the metadata.')
    parser.add_argument('video_filename',
        help='The filename of the video.')
    parser.add_argument('thumbnails_directory',
        help='The name of the directory to put thumbnails in. A sub-directory will be created here for the thumbnails for this video.')

    args = parser.parse_args()

    with open(args.metadata_filename) as file:
        video_data = json.load(file)

    video = Video.from_dict(video_data)

    thumbnails_directory = Path(args.thumbnails_directory) / video.name()
    thumbnails_directory.mkdir(exist_ok=True)

    frames = video.thumbnail_frames()

    for frame in frames:
        image = frame.to_image()
        image = image.resize((180, 120)) # Assumes original is 720x480
        image.save(thumbnails_directory / "{}.jpeg".format(math.floor(frame.time)))
