#!/usr/bin/env python3

import json
import math
from pathlib import Path

from videos_processing import Video

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Extract a thumbnail from each scene of a video.')
    parser.add_argument('metadata_filename',
        help='The filename of the metadata.')
    parser.add_argument('video_filename',
        help='The filename of the video.')
    parser.add_argument('thumbnails_directory',
        help='The name of the directory to put thumbnails in. This will be created if it does not exist.')

    args = parser.parse_args()

    thumbnails_directory = Path(args.thumbnails_directory)
    thumbnails_directory.mkdir(exist_ok=True)

    with open(args.metadata_filename) as file:
        video_data = json.load(file)

    video = Video.from_dict(video_data)

    frames = video.thumbnail_frames()

    for frame in frames:
        image = frame.to_image()
        # TODO: reformat size
        image.save(thumbnails_directory / "{}.jpeg".format(math.floor(frame.time)))
