#!/usr/bin/env python3

import json
from pathlib import Path

from videos_processing import Video

def scenes_data(video_filename):
    video = Video(video_filename)
    return video.to_dict()

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Extract scenes data from a video.')
    parser.add_argument('video_filename',
        help='The filename of the video.')
    parser.add_argument('metadata_filename',
        help='The name of the file to store data in. This file must not yet exist.')

    args = parser.parse_args()
    metadata_path = Path(args.metadata_filename)

    if metadata_path.exists():
        print("Metadata file must not be present", file=sys.stderr)
    else:
        data = scenes_data(args.video_filename)
        metadata_path.write_text(json.dumps(data, indent=2))
        print("Done")
