#!/usr/bin/env python3

import json
from pathlib import Path

from videos_processing import Video

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Extract scenes data from a video.')
    parser.add_argument('metadata_filename',
        help='The filename of the metadata.')
    parser.add_argument('video_filename',
        help='The filename of the video.')
    parser.add_argument('thumbnails_directory',
        help='The name of the directory to put thumbnails in. This will be created if it does not exist.')
